ANIMALS = [
    {
        "id": "snow_leopard",
        "name": "Snow Leopard",
        "scientific_name": "Panthera uncia",
        "hex": "#5B7FA6",
        "why": "You move through the world with an elusive grace — seen by few, remembered by all. Like the snow leopard, you leave no unnecessary trace, but the mountains know you were there.",
        "origin": "Central and South Asia, including the Himalayas, Karakoram, Hindu Kush, and Tibetan Plateau",
        "habitat": "Alpine and subalpine zones at elevations of 3,000–4,500 m; rocky terrain, cliffs, and ravines",
        "speed": "Up to 64 km/h (40 mph) in short bursts; an exceptional leaper, capable of jumps up to 15 m",
        "colours": "Smoky grey-white with dark rosettes and spots; pale underside; dense, plush fur",
        "weight": "Male: 45–55 kg; Female: 35–40 kg",
        "gender": "Solitary; females raise cubs alone for 18–22 months; litters of 2–3 cubs born in rocky dens",
        "facts": [
            "Snow leopards cannot roar — they make a unique non-aggressive vocalisation called a 'chuff' or 'prusten'.",
            "Their enormous, fur-padded paws act as natural snowshoes and help them grip icy, rocky slopes.",
            "A snow leopard's tail is nearly as long as its body and is used for balance — and as a blanket in bitter cold.",
            "They are the only big cat that lives above the snow line year-round, perfectly insulated by fur nearly 12 cm thick.",
            "Fewer than 6,000 remain in the wild, making every sighting a rare and extraordinary event.",
        ],
    },
    {
        "id": "axolotl",
        "name": "Axolotl",
        "scientific_name": "Ambystoma mexicanum",
        "hex": "#C4627A",
        "why": "You carry wonder without apology, remaining soft and open long after others have hardened. Like the axolotl, you hold the capacity to regenerate — to begin again, quietly and completely.",
        "origin": "Lake Xochimilco, Mexico City, Mexico — now critically restricted in the wild",
        "habitat": "Freshwater canals and lakes; cool, shallow, muddy-bottomed water with aquatic vegetation",
        "speed": "Slow and deliberate swimmer; uses undulating tail and four small limbs; typically 1–2 km/h",
        "colours": "Wild type is dark brown-grey with gold flecks; captive morphs range from leucistic white-pink to golden albino",
        "weight": "60–200 g (adult)",
        "gender": "Sexually mature at 12–18 months; females lay 100–1,000 eggs attached to plants; no parental care after laying",
        "facts": [
            "Axolotls are neotenic — they retain juvenile (larval) features throughout their entire lives and never fully metamorphose.",
            "They can regenerate not just limbs but also parts of their heart, lungs, and spinal cord with near-perfect fidelity.",
            "The axolotl is sacred in Aztec mythology, associated with the god Xolotl, the lightning dog who guided the dead.",
            "Wild populations have crashed by over 99% due to water pollution and the introduction of invasive carp and tilapia.",
            "Their feathery external gills — which look like a crown of red ferns — are fully functional throughout their adult life.",
        ],
    },
    {
        "id": "mantis_shrimp",
        "name": "Mantis Shrimp",
        "scientific_name": "Odontodactylus scyllarus",
        "hex": "#C45A1A",
        "why": "You perceive what others miss entirely, seeing the world in a spectrum nobody else can reach. Like the mantis shrimp, your intensity is not aggression — it is simply a refusal to be less than you are.",
        "origin": "Indo-Pacific region, from East Africa to Hawaii; most abundant in the Indian Ocean",
        "habitat": "Shallow tropical and subtropical marine environments; coral reefs, rock burrows, and sandy seafloors",
        "speed": "Strike speed of 23 m/s — one of the fastest movements in the animal kingdom, producing cavitation bubbles",
        "colours": "Vivid combination of greens, blues, reds, and oranges; among the most colourful of all crustaceans",
        "weight": "Up to 180 g",
        "gender": "Many species are monogamous and mate for life; both parents guard eggs; females brood eggs for up to 3 months",
        "facts": [
            "Mantis shrimp have 16 types of photoreceptor cells — humans have 3 — allowing them to see ultraviolet and polarised light.",
            "Their club-like appendages can strike with the force of a bullet, shattering aquarium glass and cracking crab shells.",
            "The strike generates cavitation bubbles that collapse with a shockwave powerful enough to stun prey even on a miss.",
            "Some species are called 'smashers'; others are 'spearers' that impale soft-bodied prey with spike-like appendages.",
            "Despite their fearsome reputation, they have complex social lives and can recognise individual neighbours by scent.",
        ],
    },
    {
        "id": "arctic_fox",
        "name": "Arctic Fox",
        "scientific_name": "Vulpes lagopus",
        "hex": "#4A5E7A",
        "why": "You adapt without complaint, wearing whatever the season demands and finding warmth in the most inhospitable places. Like the arctic fox, your resilience is not loudly proclaimed — it simply endures.",
        "origin": "Arctic tundra circling the globe: Alaska, Canada, Greenland, Iceland, Scandinavia, Russia",
        "habitat": "Arctic tundra, sea ice, and coastal cliffs; one of the few mammals to live year-round in the High Arctic",
        "speed": "Up to 50 km/h (31 mph); tireless long-distance travellers — one individual was tracked 3,500 km in 76 days",
        "colours": "White in winter, brown-grey in summer; the 'blue' morph remains steel-blue year-round",
        "weight": "Male: 3.5–9 kg; Female: 1.4–3.2 kg",
        "gender": "Monogamous pairs; females give birth to litters of 5–25 pups (the largest litter size of any wild canid)",
        "facts": [
            "The arctic fox can withstand temperatures as low as −70 °C before its metabolic rate even begins to increase.",
            "It has the warmest fur of any mammal relative to its size — thicker in winter than almost any land animal on Earth.",
            "Arctic foxes follow polar bears across sea ice to scavenge leftovers from their kills during the dark polar winter.",
            "Their ears are small and rounded to minimise heat loss — the opposite evolutionary strategy to the fennec fox.",
            "In boom lemming years, a single pair may raise over 20 pups; in bust years they may not breed at all.",
        ],
    },
    {
        "id": "shoebill",
        "name": "Shoebill",
        "scientific_name": "Balaeniceps rex",
        "hex": "#536878",
        "why": "You are ancient patience made visible — standing perfectly still while the world rushes past, striking only when the moment is exactly right. Like the shoebill, you need no audience to know your own magnitude.",
        "origin": "East-central Africa: South Sudan, Uganda, Tanzania, Zambia, and the Democratic Republic of Congo",
        "habitat": "Dense papyrus and reed swamps, tropical marshes, and freshwater wetlands",
        "speed": "Slow, deliberate stalker; rarely flies but can cover 150 km in migration; wingbeats slow at 150 per minute",
        "colours": "Blue-grey with darker slate tones; enormous yellow-grey bill with a reddish spot; yellow-green eyes",
        "weight": "Male: 5.6 kg; Female: 4.9 kg",
        "gender": "Solitary nesters; pairs raise only one chick (the elder sibling typically outcompetes younger ones); both parents share duties",
        "facts": [
            "The shoebill's bill — up to 24 cm long and 10 cm wide — is the third largest of any living bird, used to scoop fish whole.",
            "It stands motionless in the shallows for hours, earning it the nickname 'statue bird' among local communities.",
            "When greeting its mate at the nest, it claps its massive bill rapidly — producing a sound like machine-gun fire.",
            "Shoebills have been known to decapitate their prey before swallowing it to prevent escape.",
            "Fewer than 8,000 remain in the wild, threatened by habitat loss and poaching for the illegal pet trade.",
        ],
    },
    {
        "id": "capybara",
        "name": "Capybara",
        "scientific_name": "Hydrochoerus hydrochaeris",
        "hex": "#7A5A38",
        "why": "You are the calm at the centre of the social world — everyone is drawn to you, and you welcome them without drama. Like the capybara, your peace is not indifference; it is a conscious, generous choice.",
        "origin": "South America east of the Andes: Panama south to Argentina, most abundant in Venezuela and Brazil",
        "habitat": "Always near water — rivers, lakes, ponds, marshes, and flooded grasslands (llanos)",
        "speed": "Up to 35 km/h (22 mph) on land; excellent swimmer, can stay submerged for up to 5 minutes",
        "colours": "Coarse, sparse reddish-brown to grey-brown fur; slightly paler on the underside; nearly hairless snout",
        "weight": "Male: 50–60 kg; Female: slightly larger, up to 66 kg (the largest rodent on Earth)",
        "gender": "Dominant male leads stable groups of 10–30; females synchronise births; communal nursing of pups is common",
        "facts": [
            "The capybara is the world's largest living rodent — an adult is roughly the size of a Labrador Retriever.",
            "They are famously tolerant hosts: birds, monkeys, and even small crocodilians rest on them without being disturbed.",
            "Capybaras practise coprophagy — eating their own dung in the morning to extract maximum nutrition from plant matter.",
            "Their webbed feet make them powerful swimmers; they can sleep in the water with only their nostrils above the surface.",
            "In Brazil and Venezuela, semi-tame capybaras are found in city parks and suburban areas, largely unbothered by humans.",
        ],
    },
    {
        "id": "platypus",
        "name": "Platypus",
        "scientific_name": "Ornithorhynchus anatinus",
        "hex": "#5A4228",
        "why": "You defy every category ever built for you, existing as proof that reality is stranger and more generous than any rule. Like the platypus, you are not an anomaly — you are an argument for wonder.",
        "origin": "Eastern Australia and Tasmania; introduced to Kangaroo Island",
        "habitat": "Freshwater streams, rivers, and lakes with earthen banks for burrow-building; clean, cool water",
        "speed": "Up to 2.4 km/h swimming; uses its bill to scull rather than its webbed feet, which are tucked close to its body",
        "colours": "Dark brown dorsal fur; cream to pale grey underside; dark, leathery duck-bill; bluish-black tail",
        "weight": "Male: 1–2.4 kg; Female: 0.7–1.6 kg",
        "gender": "One of only five monotremes — egg-laying mammals; female lays 1–3 leathery eggs; male has a venomous spur on each hind leg",
        "facts": [
            "The platypus is one of only five monotremes — mammals that lay eggs rather than giving birth to live young.",
            "Its bill contains approximately 40,000 electroreceptors, allowing it to detect the electric fields of prey in murky water.",
            "When George Shaw received the first platypus specimen in 1799, he checked for stitches, convinced it was a hoax.",
            "Males have hollow spurs on their hind ankles that deliver venom strong enough to cause excruciating pain in humans.",
            "The platypus hunts entirely by electroreception underwater, closing its eyes, ears, and nose with every dive.",
        ],
    },
    {
        "id": "glass_frog",
        "name": "Glass Frog",
        "scientific_name": "Centrolenidae (family)",
        "hex": "#3A7A3A",
        "why": "You offer radical transparency — there is nothing hidden in you that you would not show to those who look closely. Like the glass frog, your openness is not vulnerability; it is a particular kind of trust.",
        "origin": "Central and South America, from southern Mexico to Bolivia and Argentina; richest diversity in Andean cloud forests",
        "habitat": "Humid tropical and subtropical rainforests; always near fast-moving mountain streams where they breed",
        "speed": "Agile leaper; moves in short, quick hops; not built for speed but for precision climbing on wet leaves",
        "colours": "Translucent lime green above; abdomen transparent enough to see the beating heart, liver, and digestive tract",
        "weight": "5–14 g depending on species",
        "gender": "Males call and guard egg clutches laid on leaves overhanging streams; tadpoles drop into water below when they hatch",
        "facts": [
            "You can see a glass frog's heart beating through its chest wall — its skin is almost entirely transparent on the underside.",
            "Researchers in 2022 discovered that glass frogs become nearly invisible by concentrating red blood cells in their liver while sleeping.",
            "Males are devoted fathers, guarding clutches of 20–30 eggs for weeks, keeping them moist by pressing their wet bodies against them.",
            "There are over 150 described species of glass frogs, many discovered only in the last two decades in unexplored cloud forests.",
            "Their transparent abdomen may serve as camouflage — the green of their internal organs matches the leaves they rest on.",
        ],
    },
    {
        "id": "fennec_fox",
        "name": "Fennec Fox",
        "scientific_name": "Vulpes zerda",
        "hex": "#8A6A30",
        "why": "You are attuned to the faintest signals — a whisper of water, a breath of wind below the sand — because your survival depends on hearing everything others miss. Like the fennec fox, your sensitivity is your superpower.",
        "origin": "Sahara Desert and North Africa, from Morocco east to the Sinai Peninsula and the Arabian Peninsula",
        "habitat": "Sandy desert, semi-arid regions with sparse vegetation; digs elaborate dens in compacted sand dunes",
        "speed": "Up to 40 km/h (25 mph); can leap up to 60 cm vertically and 120 cm horizontally from standing",
        "colours": "Sandy cream to pale gold fur; white underside; black-tipped tail; strikingly large, dark ears",
        "weight": "0.8–1.6 kg — the smallest wild canid in the world",
        "gender": "Monogamous pairs; litters of 2–5 kits; the male guards and feeds the female throughout her pregnancy and nursing",
        "facts": [
            "The fennec fox's ears — up to 15 cm long — are the largest ear-to-body ratio of any canid, used to detect prey underground.",
            "Its ears also act as radiators, dissipating heat through a dense network of blood vessels to keep cool in desert temperatures.",
            "Fennec foxes can survive indefinitely without drinking water, extracting all moisture from food — insects, rodents, and fruit.",
            "Their thick fur insulates against bitter desert nights (temperatures can fall below 0 °C) and reflects daytime heat.",
            "They communicate through an exceptionally wide vocal range: barks, purrs, chatters, shrieks, and wails.",
        ],
    },
    {
        "id": "okapi",
        "name": "Okapi",
        "scientific_name": "Okapia johnstoni",
        "hex": "#5A2A18",
        "why": "You carry your contradictions beautifully — part giraffe, part zebra, entirely your own astonishing thing. Like the okapi, you do not need to be understood to be magnificent.",
        "origin": "The Ituri Rainforest of the Democratic Republic of Congo — found nowhere else on Earth",
        "habitat": "Dense tropical rainforest at altitudes of 500–1,500 m; requires thick canopy and proximity to streams",
        "speed": "Up to 60 km/h (37 mph) when fleeing; usually slow and deliberate, browsing quietly through dense undergrowth",
        "colours": "Rich reddish-chocolate brown body; cream-and-dark-brown zebra stripes on the hindquarters and upper legs; white 'socks'",
        "weight": "200–350 kg",
        "gender": "Largely solitary; females have a longer home range than males; a single calf is born after a 14–16 month gestation",
        "facts": [
            "The okapi was unknown to science until 1901 — European naturalists dismissed African accounts of it as folklore.",
            "It is the only living relative of the giraffe, sharing the same elongated tongue (up to 45 cm) used to strip leaves and groom.",
            "Okapi have scent glands on their hooves, leaving chemical messages as they walk to communicate territory.",
            "Mother and calf communicate through infrasound — vocalisations below the threshold of human hearing.",
            "They have an extraordinary tongue long enough to wash their own eyelids and clean inside their own ears.",
        ],
    },
    {
        "id": "narwhal",
        "name": "Narwhal",
        "scientific_name": "Monodon monoceros",
        "hex": "#3A5E7A",
        "why": "You carry something singular and strange that the world has never quite known how to classify — and that is exactly the point. Like the narwhal, your most distinctive feature is not a weapon, but a kind of instrument.",
        "origin": "High Arctic waters around Canada, Greenland, Norway, and Russia",
        "habitat": "Deep Arctic Ocean and fjords; winters beneath pack ice, summers in open coastal waters",
        "speed": "Up to 25 km/h (15 mph); can dive to depths exceeding 1,500 m — among the deepest dives recorded for any cetacean",
        "colours": "Mottled blue-grey and white; adults become paler with age; calves are uniformly dark grey-blue",
        "weight": "800–1,600 kg; males heavier",
        "gender": "Polygynous; males use tusks in jousting displays for females; one calf born after 14–15 months gestation",
        "facts": [
            "The narwhal's 'horn' is actually a spiralling canine tooth that pierces through the upper lip — found almost exclusively in males.",
            "The tusk can grow up to 3 m long and contains up to 10 million nerve endings, possibly used to sense salinity and temperature.",
            "Medieval Europeans believed narwhal tusks were unicorn horns with magical properties; they were worth more than gold by weight.",
            "Narwhals spend up to 5 months a year under dense Arctic pack ice, navigating in near-total darkness.",
            "They can hold their breath for over 25 minutes and survive under sea ice by finding small breathing holes called 'savsats'.",
        ],
    },
    {
        "id": "manta_ray",
        "name": "Manta Ray",
        "scientific_name": "Mobula birostris",
        "hex": "#1A3050",
        "why": "You move through depth and darkness with effortless, unhurried grace, requiring nothing but open water and your own momentum. Like the manta ray, you are most yourself when you stop trying to be small.",
        "origin": "Tropical and subtropical oceans worldwide; particularly abundant in the Coral Triangle, Maldives, and Azores",
        "habitat": "Open ocean (pelagic) and coral reef environments; undertakes long migrations following plankton blooms",
        "speed": "Cruising at 9–24 km/h; can breach completely out of the water, leaping up to 2 m into the air",
        "colours": "Dark black or deep blue-grey dorsal side; white ventral surface with unique dark spot patterns used for identification",
        "weight": "1,350–2,700 kg; wingspan up to 7 m",
        "gender": "Give birth to a single live pup every 2–3 years after a 12–13 month gestation; young are born already fully formed",
        "facts": [
            "Manta rays have the largest brain-to-body ratio of any cold-blooded fish — and pass the mirror self-recognition test.",
            "Each manta has a unique pattern of spots on its white underside, like a fingerprint, used by researchers to track individuals.",
            "They visit cleaning stations on coral reefs where wrasse fish remove parasites — sometimes queuing patiently for their turn.",
            "Mantas are filter feeders, consuming up to 27 kg of zooplankton per day through their enormous cephalic fins.",
            "They are listed as vulnerable globally; their gill plates are highly valued in Chinese medicine, driving unsustainable fishing.",
        ],
    },
    {
        "id": "clouded_leopard",
        "name": "Clouded Leopard",
        "scientific_name": "Neofelis nebulosa",
        "hex": "#6A5838",
        "why": "You move between worlds — earth and canopy, shadow and dappled light — belonging fully to neither and perfectly to both. Like the clouded leopard, you are most at home in the in-between.",
        "origin": "Southeast Asia and southern China; Himalayan foothills from Nepal to southern China, down through Borneo and Sumatra",
        "habitat": "Primary and secondary tropical and subtropical forest; both lowland and highland rainforest up to 2,500 m",
        "speed": "Excellent arboreal climber; can descend head-first and hang from branches by its hind feet; agile sprinter in canopy",
        "colours": "Tawny yellow-grey with large, irregularly shaped dark 'clouds' outlined in black; white underside; striped face",
        "weight": "Male: 15–23 kg; Female: 11–14 kg",
        "gender": "Solitary; extremely difficult to breed in captivity due to male aggression; females give birth to 1–5 cubs",
        "facts": [
            "The clouded leopard has the longest canine teeth relative to skull size of any living felid — proportionally longer than a tiger's.",
            "Unlike most cats, it can rotate its ankles nearly 180 degrees, allowing it to climb down trees head-first like a squirrel.",
            "Its wide, padded paws and extremely flexible joints allow it to hang from branches using only its hind legs.",
            "Two distinct species exist: the Sunda clouded leopard of Borneo and Sumatra was only recognised as a separate species in 2006.",
            "Almost nothing is known about its behaviour in the wild — it is so secretive that camera trap footage is exceptionally rare.",
        ],
    },
    {
        "id": "quokka",
        "name": "Quokka",
        "scientific_name": "Setonix brachyurus",
        "hex": "#8A7030",
        "why": "You greet each moment as if it were the best one yet — not because life is simple, but because you have decided that warmth costs nothing and gives everything. Like the quokka, your joy is a choice, and a generous one.",
        "origin": "Southwestern Australia; mainly Rottnest Island and Bald Island off the coast of Perth",
        "habitat": "Dense coastal heath, scrubland, and forest near fresh water; uses tunnels through vegetation as runways",
        "speed": "Up to 20 km/h (12 mph); hops like a small kangaroo; highly agile through dense scrub",
        "colours": "Rough brownish-grey fur with paler underside; short, rounded ears; small, upturned mouth giving a permanent 'smile'",
        "weight": "2.5–5 kg",
        "gender": "Females can pause a developing embryo (embryonic diapause) and resume pregnancy when conditions improve; one joey at a time",
        "facts": [
            "The quokka's apparent smile is an anatomical feature, not an expression — but they are genuinely curious and approachable.",
            "Dutch explorer Willem de Vlamingh mistook them for giant rats in 1696, naming the island 'Ratte nest' (Rottnest).",
            "In extreme heat or drought, a mother may release a joey from her pouch — a hard survival strategy that has evolved over millennia.",
            "They are nocturnal and largely vegetarian, surviving on tough grasses and leaves with very little water.",
            "Quokkas on Rottnest Island have lost their fear of humans, making them the most selfie-sought animal in Australia.",
        ],
    },
    {
        "id": "tardigrade",
        "name": "Tardigrade",
        "scientific_name": "Phylum Tardigrada",
        "hex": "#6A5878",
        "why": "You have survived every extinction event this planet has thrown at life — not through armour or aggression, but by becoming still, small, and almost nothing, then returning. Like the tardigrade, your endurance is a form of philosophy.",
        "origin": "Everywhere on Earth — every continent including Antarctica, every ocean, every mountain and valley",
        "habitat": "Thin films of water on mosses, lichens, leaf litter, soil, and marine sediment; ubiquitous in damp terrestrial environments",
        "speed": "Roughly 1 mm per minute in normal conditions; one of the slowest animals relative to body size",
        "colours": "Translucent to pale yellow-pink when active; opaque and shrunken in cryptobiosis (the 'tun' state)",
        "weight": "1–20 micrograms (adults of the largest species); typically 0.1–1.5 mm in length",
        "gender": "Most species reproduce sexually; some are parthenogenetic; eggs are often deposited in the shed cuticle during moulting",
        "facts": [
            "In their cryptobiotic 'tun' state, tardigrades can survive temperatures from −272 °C to +150 °C, radiation 1,000x lethal to humans.",
            "They are the first known animals to survive direct exposure to the vacuum and radiation of outer space.",
            "A tardigrade can lose 97% of its water content, shrink into a barrel shape, and revive from this state centuries later.",
            "Tardigrades have been found alive in Antarctic ice, Himalayan summits, deep ocean trenches, and hot springs.",
            "Their genome contains roughly 17.5% horizontal gene transfer from bacteria — genes borrowed from other organisms over deep time.",
        ],
    },
    {
        "id": "resplendent_quetzal",
        "name": "Resplendent Quetzal",
        "scientific_name": "Pharomachrus mocinno",
        "hex": "#1A6A38",
        "why": "You are what happens when beauty stops apologising for itself — iridescent, improbable, and unwilling to be caged without dying. Like the resplendent quetzal, freedom is not a preference for you; it is a biological requirement.",
        "origin": "Cloud forests of Central America: from southern Mexico to western Panama",
        "habitat": "Montane cloud forests at 1,500–3,000 m elevation; requires large areas of old-growth forest with avocado-family trees",
        "speed": "Agile flier through dense forest; undulating flight pattern; not built for sustained speed",
        "colours": "Iridescent emerald green body and head; crimson belly; brilliant green tail feathers (males) up to 1 m long; golden-green crest",
        "weight": "Male: 210–225 g; Female: 185–220 g",
        "gender": "Monogamous pairs; both sexes incubate eggs but only the male's tail feathers hang out of the nest hole; 2–3 eggs per clutch",
        "facts": [
            "The resplendent quetzal was so sacred to the Maya and Aztec that killing one was punishable by death.",
            "It is the national bird and symbol of Guatemala; the Guatemalan currency is named 'the quetzal' in its honour.",
            "Male tail plumes can reach up to 1 metre in length — longer than the bird's body — and are shed and re-grown annually.",
            "Quetzals are exceptionally difficult to keep in captivity; historically, captive birds died quickly, reinforcing their association with freedom.",
            "They are entirely dependent on wild avocado (Lauraceae) fruits, which they swallow whole and regurgitate seeds of — making them vital forest regenerators.",
        ],
    },
    {
        "id": "aye_aye",
        "name": "Aye-aye",
        "scientific_name": "Daubentonia madagascariensis",
        "hex": "#2A1A10",
        "why": "You were built for a problem no one else could solve, with tools so peculiar they look like mistakes until you watch them work. Like the aye-aye, your strangeness is not a flaw — it is an elegant solution.",
        "origin": "Madagascar; once thought extinct, now known to inhabit the entire island",
        "habitat": "Rainforest, dry deciduous forest, and coastal mangroves; predominantly arboreal, spending nearly all its time in trees",
        "speed": "Slow mover; travels 2–4 km per night foraging through the canopy",
        "colours": "Coarse, shaggy dark brown to black fur with white guard hairs; enormous orange eyes; bat-like ears; rat-like incisors",
        "weight": "2.5–2.9 kg",
        "gender": "Solitary; females are dominant; home ranges overlap; females mate with multiple males; a single offspring born after 170 days",
        "facts": [
            "The aye-aye is the world's largest nocturnal primate, filling the ecological niche of a woodpecker without any woodpecker anatomy.",
            "Its elongated middle finger — skeletal and witch-like — is used to tap on wood at 8 Hz to echolocate hollow chambers full of grubs.",
            "It chews a hole in the bark with its continuously growing rodent-like incisors, then hooks out larvae with its thin middle finger.",
            "In Malagasy tradition, the aye-aye is an omen of death; some communities kill them on sight, threatening their survival.",
            "Its bizarre combination of features led early naturalists to classify it wrongly for decades — it is in fact a primate, related to lemurs.",
        ],
    },
    {
        "id": "blue_dragon",
        "name": "Blue Dragon",
        "scientific_name": "Glaucus atlanticus",
        "hex": "#2848A0",
        "why": "You drift on the surface tension between worlds — sky above, ocean below — small, luminous, and far more dangerous than you appear. Like the blue dragon, the most extraordinary things are often the ones you nearly stepped on.",
        "origin": "Temperate and tropical waters of the Atlantic, Pacific, and Indian Oceans; occasionally washed ashore on beaches worldwide",
        "habitat": "Open ocean surface; floats upside-down on the surface tension, carried by wind and currents",
        "speed": "Entirely at the mercy of wind and current; no directed locomotion — a beautiful passenger of the sea",
        "colours": "Vivid blue and silver-grey; the blue ventral side faces up (matching sky); silver dorsal side faces down (matching ocean)",
        "weight": "Less than 0.1 g; body length 2–4 cm",
        "gender": "Hermaphroditic; each individual produces both eggs and sperm; they exchange sperm with any partner they meet; eggs float in strings",
        "facts": [
            "The blue dragon stores stinging cells from its prey (Portuguese man o' war) in finger-like appendages called cerata — concentrating the venom.",
            "Its sting is more potent than the man o' war itself because the nematocysts are concentrated rather than spread across tentacles.",
            "It floats by swallowing an air bubble and storing it in a gas-filled sac in its stomach, always riding at the surface.",
            "Its blue-and-silver colouration is a form of counter-shading: from above it looks like ocean, from below it looks like sky.",
            "This tiny sea slug preys on creatures many times its size — including the by-the-wind-sailor and the violet snail.",
        ],
    },
    {
        "id": "sun_bear",
        "name": "Sun Bear",
        "scientific_name": "Helarctos malayanus",
        "hex": "#1A0E06",
        "why": "You ask for very little and appreciate everything — a hollow tree, a hive of honey, a warm patch of sunlight. Like the sun bear, your contentment is not simplicity; it is a refined and particular wisdom.",
        "origin": "Southeast Asia: Bangladesh, India, and southern China south through the Malay Peninsula to Borneo and Sumatra",
        "habitat": "Tropical lowland rainforest and hill forest; largely arboreal, sleeping and sunbathing in nests in trees",
        "speed": "Agile climber; moves quickly through forest; can run at up to 48 km/h (30 mph) in short bursts",
        "colours": "Short, sleek black fur; distinctive U-shaped orange or cream chest patch; short muzzle; small rounded ears",
        "weight": "Male: 27–65 kg; Female: 20–40 kg — the smallest bear species in the world",
        "gender": "Non-seasonal breeding; females give birth to 1–2 cubs in dens; cubs stay with mother for 2–3 years",
        "facts": [
            "The sun bear has the longest tongue relative to body size of any bear — up to 25 cm — perfectly designed for extracting honey.",
            "It is the smallest of all eight bear species, yet pound for pound one of the most powerful climbers in the animal kingdom.",
            "Sun bears are expert beekeepers of the forest: they can smell a hive from several kilometres and tear apart logs to reach it.",
            "Their loose, baggy skin evolved as a defence — when grabbed, they can turn almost entirely within their own skin to bite back.",
            "They create 'sun nests' — platforms of bent branches high in trees where they lounge and sleep in the canopy warmth.",
        ],
    },
    {
        "id": "leafy_sea_dragon",
        "name": "Leafy Sea Dragon",
        "scientific_name": "Phycodurus eques",
        "hex": "#4A7A38",
        "why": "You are the art of becoming invisible through extravagance — more leaf than animal, more performance than creature. Like the leafy sea dragon, your camouflage is not hiding; it is a masterclass in belonging.",
        "origin": "Southern and western coasts of Australia, from Kangaroo Island to the Houtman Abrolhos Islands",
        "habitat": "Rocky reefs and kelp forests at depths of 3–50 m; requires calm, clear, temperate coastal waters",
        "speed": "Propelled by nearly transparent fins; moves at under 150 m per hour — one of the slowest fish in the ocean",
        "colours": "Yellow-green with leaf-like appendages edged in white and brown; individual colouring varies with diet and habitat",
        "weight": "Up to 150 g; body length 20–35 cm",
        "gender": "Males carry eggs on a spongy brood patch beneath their tail; females deposit 250–300 eggs; males incubate for 4–6 weeks",
        "facts": [
            "Leafy sea dragons are entirely unique to Australia and are the marine emblem of South Australia.",
            "Their leaf-like lobes serve purely as camouflage — they play no role in propulsion and are not used for steering.",
            "They have no teeth and no stomach, eating continuously — up to 3,000 mysid shrimp per day — just to survive.",
            "Like seahorses, males carry and hatch the eggs; the female has no further involvement after depositing them.",
            "They are impossible to keep alive in captivity for long without specialised, meticulously maintained aquatic environments.",
        ],
    },
    {
        "id": "mandrill",
        "name": "Mandrill",
        "scientific_name": "Mandrillus sphinx",
        "hex": "#1A4A20",
        "why": "You wear your status openly, your colours brightening with your confidence and dimming when life has been unkind. Like the mandrill, you do not pretend — your face has always been an honest map of your inner world.",
        "origin": "West-central Africa: Cameroon, Gabon, Equatorial Guinea, and the Republic of Congo",
        "habitat": "Tropical rainforest and adjacent gallery forest; largely terrestrial but sleeps in trees",
        "speed": "Up to 40 km/h (25 mph) on the ground; travels 10+ km per day foraging in large groups",
        "colours": "Olive-brown body; male has vivid red and blue facial ridges, golden beard, and multicoloured rump; female is duller",
        "weight": "Male: 19–37 kg; Female: 10–15 kg — the world's largest monkey",
        "gender": "Multi-male, multi-female groups ('hordes') of up to 800 individuals; dominant males have the brightest colouration",
        "facts": [
            "The mandrill is the world's largest monkey; adult males are among the most dramatically coloured of all mammals.",
            "The intensity of a male's facial colour is directly linked to his testosterone level — dominant males are literally more vivid.",
            "Mandrills communicate chemical information through sternal scent glands, and social status is encoded in their scent profile.",
            "They form the largest non-human primate groups on Earth, sometimes assembling in 'supergroups' of up to 800 individuals.",
            "Despite their fearsome appearance, mandrills have cheek pouches allowing them to collect food quickly and eat it safely later.",
        ],
    },
    {
        "id": "star_nosed_mole",
        "name": "Star-nosed Mole",
        "scientific_name": "Condylura cristata",
        "hex": "#3A2018",
        "why": "You have traded vision for sensation, building a picture of your world through touch alone, faster than any eye could process it. Like the star-nosed mole, your intelligence lies in the questions no one else thought to ask.",
        "origin": "Eastern North America, from the Canadian Maritimes and Quebec south to Georgia and the Appalachians",
        "habitat": "Wet lowland areas — swamps, marshy meadows, stream banks, and boggy woodland with moist, loose soil",
        "speed": "Identifies, catches, and consumes a prey item in as little as 120 milliseconds — the fastest-eating mammal known",
        "colours": "Densely furred dark brown-black body; pink, fleshy 22-ray star on the nose; broad, spade-like forelimbs; scaly tail",
        "weight": "35–75 g",
        "gender": "Forms monogamous pairs in winter; litters of 2–7 young born in spring; young are functionally blind at birth",
        "facts": [
            "The star on its nose has 22 fleshy rays containing over 25,000 minute sensory receptors called Eimer's organs.",
            "It is the fastest-eating mammal on Earth, processing prey in 120 milliseconds — faster than the human eye can follow.",
            "The star is so sensitive it can detect the electrical fields of prey in water, functioning like a shark's lateral line.",
            "Star-nosed moles are semi-aquatic and excellent swimmers, hunting aquatic invertebrates in streams and ponds beneath ice.",
            "Neuroscientists study them intensively: their star occupies a disproportionately massive portion of their brain's sensory cortex.",
        ],
    },
    {
        "id": "fossa",
        "name": "Fossa",
        "scientific_name": "Cryptoprocta ferox",
        "hex": "#6A5030",
        "why": "You are the apex of a world unto itself — shaped by isolation into something neither quite cat nor quite mongoose, answering only to Madagascar's own logic. Like the fossa, you are the product of a story told by no one else.",
        "origin": "Madagascar — endemic, found nowhere else on Earth; ranges across most of the island",
        "habitat": "All forest types on Madagascar: rainforest, dry deciduous forest, and spiny thicket; needs large contiguous forest areas",
        "speed": "Up to 35 km/h (22 mph); an exceptional climber using semi-retractile claws and flexible ankles; active both day and night",
        "colours": "Short, uniform reddish-brown to dark brown fur; pale underside; long, cat-like tail nearly equal to body length",
        "weight": "Male: 6–8.6 kg; Female: 5–6.8 kg — the largest carnivore native to Madagascar",
        "gender": "Females mate in trees in communal 'mating trees'; one female may mate with several males over multiple days",
        "facts": [
            "The fossa is the top predator of Madagascar, capable of hunting lemurs up to its own body weight by leaping through the canopy.",
            "For decades, scientists debated whether it was a cat, a civet, or a mongoose — it is most closely related to the mongoose family.",
            "Juvenile females go through a phase of transient masculinisation, temporarily developing male-like genitalia — unique among carnivores.",
            "Its semi-retractile claws and ankle flexibility allow it to descend trees head-first, like a clouded leopard.",
            "With only 10% of Madagascar's original forest remaining, the fossa faces severe range contraction and is classified as vulnerable.",
        ],
    },
    {
        "id": "secretary_bird",
        "name": "Secretary Bird",
        "scientific_name": "Sagittarius serpentarius",
        "hex": "#6A6050",
        "why": "You walk where others fly — upright, deliberate, and devastatingly effective — bringing precision to a world that expects grace from the sky alone. Like the secretary bird, your power is in the method, not the spectacle.",
        "origin": "Sub-Saharan Africa, from Senegal and The Gambia east to Ethiopia and Somalia, south to South Africa",
        "habitat": "Open grassland, savanna, and lightly wooded areas; avoids dense forest and very arid desert",
        "speed": "Walks 20–30 km per day on foot; kicks with a force of 5 times its body weight — 195 N delivered in 15 milliseconds",
        "colours": "Pale grey body; long black flight feathers; bare red-orange facial skin; long black crest feathers; pinkish-white legs",
        "weight": "2.3–4.3 kg; wingspan up to 2.1 m",
        "gender": "Monogamous, life-long pairs; nest high in flat-topped acacia trees; 2–3 eggs; both parents incubate and feed chicks",
        "facts": [
            "The secretary bird kills snakes — including cobras and adders — by stamping on them with explosive, precisely aimed kicks.",
            "Each stamping kick delivers a force of approximately 195 newtons in under 15 milliseconds, far too fast for a snake to react.",
            "It hunts entirely on foot, walking up to 30 km per day through grassland, flushing and stamping on prey.",
            "Its name may come from the quill-like crest feathers resembling the quill pens secretaries once tucked behind their ears.",
            "The secretary bird is represented on the coat of arms of Sudan and South Africa, symbols of protection and vigilance.",
        ],
    },
    {
        "id": "saiga_antelope",
        "name": "Saiga Antelope",
        "scientific_name": "Saiga tatarica",
        "hex": "#8A7848",
        "why": "You have crossed ice ages and outlasted empires, roaming the same open steppes where mammoths once walked beside you. Like the saiga, your survival is ancient knowledge written in bone and motion, not strategy.",
        "origin": "Central Asian steppes: Kazakhstan, Russia (Kalmykia), Mongolia, and Uzbekistan",
        "habitat": "Open steppe, semi-desert, and arid grasslands; migrates seasonally across hundreds of kilometres",
        "speed": "Up to 80 km/h (50 mph); undertakes migrations of up to 1,000 km between summer and winter ranges",
        "colours": "Cinnamon-brown in summer, pale grey-white in winter; cream underside; males have distinctive ringed amber horns",
        "weight": "Male: 32–51 kg; Female: 21–41 kg",
        "gender": "Males are polygynous, forming harems of 5–50 females; males fight and may die of exhaustion during the rut; females birth twins",
        "facts": [
            "The saiga's bulbous, inflatable nose filters out dust in summer and warms frigid air in winter — one of the strangest faces in nature.",
            "It is a Pleistocene relict, sharing the steppe with woolly mammoths and cave lions for tens of thousands of years.",
            "In 2015, a mass die-off killed 200,000 saiga — over 60% of the global population — in just three weeks, from a bacterium triggered by unusual warmth.",
            "Males grow elegantly ringed, translucent amber horns prized in traditional Chinese medicine — driving severe poaching pressure.",
            "Conservation efforts have driven dramatic recovery in Kazakhstan: numbers rose from 50,000 in 2003 to over 1.3 million by 2022.",
        ],
    },
]
